# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://vishalbakshi.github.io/nbdev_template_vb/"

git_url = "https://github.com/vishalbakshi/nbdev_template_vb/tree/{branch}/"

def custom_doc_links(name): return None
